"""LocalPlay game catalog — static game metadata + Revelry bridge game-type sets.

Extracted from main.py (it was ~710 inline lines there). This is DATA, not
logic: per-game capabilities, host-app support, setup schemas, and the
game-type allowlists the Revelry bridge validates against. Policy filtering
lives in host_app_catalog_policy.py; rules text attaches via game_rules.
"""
import config
from bingo_engine import DEFAULT_BINGO_PATTERNS
from game_rules import attach_rules
from generic_prompt_engine import catalog_entries as generic_prompt_catalog_entries
from housie_engine import DEFAULT_HOUSIE_PATTERNS
from tv_catalog import attach_tv_capabilities

REVELRY_PARTY_GAME_TYPES = ("quiz", "wmlt", "drawing", "housie", "chit_pull", "party_quests")
REVELRY_PARTY_GAME_TYPES_ERROR = 'game_type must be "quiz", "wmlt", "drawing", "housie", "chit_pull", or "party_quests"'
REVELRY_PARTY_GAME_START_TYPES = (
    *REVELRY_PARTY_GAME_TYPES,
    "musical_chairs",
    "bluff",
    "find_someone",
    "mafia",
    "would_you_rather",
    "never_have_i_ever",
    "word_association",
    "acronym",
    "photo_clue",
    "poker",
)
REVELRY_PARTY_GAME_START_TYPES_ERROR = (
    "game_type must be one of "
    + ", ".join(f'"{game_type}"' for game_type in REVELRY_PARTY_GAME_START_TYPES)
)

GAME_CATALOG = [
    {
        "id": "quiz",
        "game_type": "quiz",
        "runtime_type": "quiz",
        "title": "AI Quiz",
        "description": "A fast trivia room with multiple-choice questions.",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_ai_generation": True,
        "supports_custom_content": True,
        "supports_images": True,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": True,
        "creation_modes": ["manual", "ai"],
        "default_content_available": True,
        "embedded_authoring_supported": True,
        "content_schema": {
            "kind": "quiz",
            "question_count": {"min": 1, "max": 50},
            "supported_media": ["image"],
        },
    },
    {
        "id": "wmlt",
        "game_type": "wmlt",
        "runtime_type": "wmlt",
        "title": "Most Likely To",
        "description": "Vote on who best matches each prompt.",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": False,
        "supports_ai_generation": True,
        "creation_modes": ["template", "manual", "ai"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "prompt_list",
            "prompt_count": {"min": 1, "max": 50},
            "supported_media": [],
        },
    },
    {
        "id": "drawing",
        "game_type": "drawing",
        "runtime_type": "drawing",
        "title": "Drawing Game",
        "description": "Draw secret prompts while everyone guesses.",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": False,
        "supports_ai_generation": True,
        "creation_modes": ["template", "manual", "ai"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "prompt_list",
            "prompt_count": {"min": 1, "max": 50},
            "supported_media": [],
        },
        "config_schema": {
            "time_limit": {"min": 5, "max": 60, "default": 30},
        },
    },
    {
        "id": "housie",
        "game_type": "housie",
        "runtime_type": "housie",
        "title": "Housie",
        "description": "Classic 90-ball number calling with tickets and prize claims.",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["manual", "template"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "housie_setup",
            "ticket_layout": "housie_3x9_15",
            "number_range": {"min": 1, "max": 90},
            "patterns": [pattern["id"] for pattern in DEFAULT_HOUSIE_PATTERNS],
            "play_modes": ["beginner", "pro"],
            "caller_modes": ["manual", "auto"],
            "claim_requires_latest_call": True,
            "supported_media": [],
        },
    },
    {
        "id": "bingo",
        "game_type": "bingo",
        "runtime_type": "bingo",
        "title": "Bingo",
        "description": "Create a custom Bingo board with your own words, phrases, or images.",
        "launchable": True,
        "host_app_supported": False,
        "supported_host_apps": [],
        "supports_custom_content": True,
        "supports_images": True,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["manual", "template"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "bingo_setup",
            "layouts": ["bingo_5x5_free", "bingo_5x5"],
            "item_kinds": ["text", "emoji", "image"],
            "deck_count": {"min": 24, "max": 120},
            "patterns": [pattern["id"] for pattern in DEFAULT_BINGO_PATTERNS],
            "supported_media": ["image"],
        },
        "enabled": config.BINGO_ENABLED,
    },
    {
        "id": "baby_bingo",
        "game_type": "bingo",
        "runtime_type": "bingo",
        "title": "Baby Bingo",
        "description": "A ready-made baby shower Bingo board with gifts, moments, and tiny socks.",
        "launchable": True,
        "host_app_supported": False,
        "supported_host_apps": [],
        "supports_custom_content": True,
        "supports_images": True,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["template", "manual"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "bingo_setup",
            "ruleset": "baby_bingo",
            "layouts": ["bingo_5x5_free", "bingo_5x5"],
            "item_kinds": ["text", "emoji", "image"],
            "deck_count": {"min": 24, "max": 120},
            "patterns": [pattern["id"] for pattern in DEFAULT_BINGO_PATTERNS],
            "supported_media": ["image"],
        },
        "enabled": config.BINGO_ENABLED,
    },
    {
        "id": "wedding_bingo",
        "game_type": "bingo",
        "runtime_type": "bingo",
        "title": "Wedding Bingo",
        "description": "A ready-made wedding reception board: first dance, bouquet toss, and someone crying.",
        "launchable": True,
        "host_app_supported": False,
        "supported_host_apps": [],
        "supports_custom_content": True,
        "supports_images": True,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["template", "manual"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "bingo_setup",
            "ruleset": "wedding_bingo",
            "layouts": ["bingo_5x5_free", "bingo_5x5"],
            "item_kinds": ["text", "emoji", "image"],
            "deck_count": {"min": 24, "max": 120},
            "patterns": [pattern["id"] for pattern in DEFAULT_BINGO_PATTERNS],
            "supported_media": ["image"],
        },
        "enabled": config.BINGO_ENABLED,
    },
    {
        "id": "holiday_bingo",
        "game_type": "bingo",
        "runtime_type": "bingo",
        "title": "Holiday Bingo",
        "description": "Ugly sweaters, tangled lights, and the annual leftovers debate.",
        "launchable": True,
        "host_app_supported": False,
        "supported_host_apps": [],
        "supports_custom_content": True,
        "supports_images": True,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["template", "manual"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "bingo_setup",
            "ruleset": "holiday_bingo",
            "layouts": ["bingo_5x5_free", "bingo_5x5"],
            "item_kinds": ["text", "emoji", "image"],
            "deck_count": {"min": 24, "max": 120},
            "patterns": [pattern["id"] for pattern in DEFAULT_BINGO_PATTERNS],
            "supported_media": ["image"],
        },
        "enabled": config.BINGO_ENABLED,
    },
    {
        "id": "road_trip_bingo",
        "game_type": "bingo",
        "runtime_type": "bingo",
        "title": "Road Trip Bingo",
        "description": "Wrong turns, playlist arguments, and cows in a field.",
        "launchable": True,
        "host_app_supported": False,
        "supported_host_apps": [],
        "supports_custom_content": True,
        "supports_images": True,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["template", "manual"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "bingo_setup",
            "ruleset": "road_trip_bingo",
            "layouts": ["bingo_5x5_free", "bingo_5x5"],
            "item_kinds": ["text", "emoji", "image"],
            "deck_count": {"min": 24, "max": 120},
            "patterns": [pattern["id"] for pattern in DEFAULT_BINGO_PATTERNS],
            "supported_media": ["image"],
        },
        "enabled": config.BINGO_ENABLED,
    },
    {
        "id": "musical_chairs",
        "game_type": "musical_chairs",
        "runtime_type": "musical_chairs",
        "title": "Musical Chairs",
        "description": "Music plays, then stops. Race to grab a chair. Last one standing wins.",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": False,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "musical_chairs_setup",
            "music_modes": ["builtin", "external"],
            "music_styles": ["upbeat", "jazzy", "suspenseful", "retro", "tropical"],
            "music_tracks": ["hosted_ionos"],
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_MUSICAL_CHAIRS_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "music_window_seconds": {"min": 60, "max": 300, "default_min": 60, "default_max": 300},
        },
    },
    {
        "id": "bluff",
        "game_type": "bluff",
        "runtime_type": "bluff",
        "title": "Bluff",
        "description": "A big-group card game of bold claims and louder challenges.",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": False,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "card_game_setup",
            "deck": "standard_52",
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_BLUFF_PLAYERS, "max": 20},
            "challenge_window_seconds": {"min": 5, "max": 60, "default": 12},
            "turn_time_seconds": {"min": 10, "max": 120, "default": 30},
        },
    },
    {
        "id": "two_truths",
        "game_type": "two_truths",
        "runtime_type": "two_truths",
        "title": "Two Truths and a Lie",
        "description": "Players submit three statements and the room guesses the lie.",
        "launchable": True,
        "host_app_supported": False,
        "supported_host_apps": [],
        "supports_custom_content": False,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "submission_game_setup",
            "statements_per_player": 3,
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_TWO_TRUTHS_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "submission_time_seconds": {"min": 60, "max": 600, "default": 180},
            "vote_time_seconds": {"min": 10, "max": 90, "default": 30},
        },
    },
    {
        "id": "story_chain",
        "game_type": "story_chain",
        "runtime_type": "story_chain",
        "title": "Story Chain",
        "description": "Take turns adding sentences, then reveal the final story.",
        "launchable": True,
        "host_app_supported": False,
        "supported_host_apps": [],
        "supports_custom_content": False,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "sequential_creative_setup",
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_STORY_CHAIN_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "turn_time_seconds": {"min": 20, "max": 120, "default": 45},
            "sentence_max_chars": {"min": 60, "max": 280, "default": 180},
            "visibility_modes": ["full_context", "last_sentence_only"],
        },
    },
    {
        "id": "common_ground",
        "game_type": "common_ground",
        "runtime_type": "common_ground",
        "title": "Common Ground",
        "description": "Teams find shared facts, reveal them, and vote on the best ones.",
        "launchable": True,
        "host_app_supported": False,
        "supported_host_apps": [],
        "supports_custom_content": False,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "team_icebreaker_setup",
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_COMMON_GROUND_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "team_size": {"min": 2, "max": 6, "default": 3},
            "rounds": {"min": 1, "max": 10, "default": 5},
            "discussion_time_seconds": {"min": 30, "max": 300, "default": 90},
            "vote_time_seconds": {"min": 10, "max": 90, "default": 30},
            "vote_categories": ["funniest", "most_surprising", "most_specific"],
        },
    },
    {
        "id": "find_someone",
        "game_type": "find_someone",
        "runtime_type": "find_someone",
        "title": "Find Someone Who",
        "description": "A social bingo grid that gets guests talking throughout the party.",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["template", "settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "checkin_friendly": True,
        "can_start_with_first_player": True,
        "supports_late_join": True,
        "default_for_checkin_supported": True,
        "auto_start_on_first_checkin_default": True,
        "checkin_join_policy": "resume_or_join",
        "content_schema": {
            "kind": "social_bingo_setup",
            "layouts": ["bingo_5x5_free", "bingo_5x5", "bingo_4x4"],
            "confirmation_modes": ["tap_confirm", "honor"],
            "patterns": ["first_line", "four_corners", "blackout"],
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_FIND_SOMEONE_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "round_time_seconds": {"min": 120, "max": 7200, "default": 900},
            "checkin_default_supported": True,
            "auto_start_on_first_checkin_default": True,
            "default_for_checkin": {"default": False},
            "checkin_join_policy": {"default": "resume_or_join", "options": ["resume_or_join", "host_started_only"]},
        },
    },
    {
        "id": "who_am_i",
        "game_type": "who_am_i",
        "runtime_type": "who_am_i",
        "title": "Who Am I?",
        "description": "Reveal clues while everyone races to guess the mystery person, place, or thing.",
        "launchable": True,
        "host_app_supported": False,
        "supported_host_apps": [],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": True,
        "supports_ai_generation": True,
        "creation_modes": ["template", "manual", "ai"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "clue_guessing_setup",
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_WHO_AM_I_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "rounds": {"min": 3, "max": 25, "default": 5},
            "clues_per_round": {"min": 3, "max": 6, "default": 5},
            "points_by_clue": [500, 400, 300, 200, 100],
            "max_guesses_per_clue": {"min": 1, "max": 5, "default": 2},
        },
    },
    {
        "id": "chit_pull",
        "game_type": "chit_pull",
        "runtime_type": "chit_pull",
        "title": "Random Chit",
        "description": "Randomly pick a player and a funny question, action, or mini challenge.",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": True,
        "supports_ai_generation": True,
        "creation_modes": ["template", "manual", "ai"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "chit_pull_setup",
            "chit_count": {"min": 5, "max": 200},
            "categories": ["question", "action", "funny_face", "mini_challenge", "group"],
            "safe_levels": ["kids", "family", "work_safe", "spicy"],
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_CHIT_PULL_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "rounds": {"min": 5, "max": 100, "default": 20},
            "turn_time_seconds": {"min": 10, "max": 120, "default": 30},
        },
    },
    {
        "id": "mafia",
        "game_type": "mafia",
        "runtime_type": "mafia",
        "engine_family": "mafia",
        "title": "Mafia",
        "description": "Secret roles, night kills, and daytime accusations. Find the Mafia before they outnumber you.",
        "status": "gamma",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": False,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "mafia_setup_v1",
            "supported_media": [],
        },
        "result_summary_schema": "mafia_result_v1",
        "config_schema": {
            "players": {"min": config.MIN_MAFIA_PLAYERS, "max": 15},
            "night_timer_seconds": {"min": 15, "max": 60, "default": 30},
            "discussion_timer_seconds": {"min": 30, "max": 180, "default": 90},
            "vote_timer_seconds": {"min": 15, "max": 60, "default": 30},
            "role_reveal_seconds": {"min": 5, "max": 20, "default": 10},
        },
    },
    {
        "id": "party_quests",
        "game_type": "party_quests",
        "runtime_type": "party_quests",
        "engine_family": "ambient_social",
        "title": "Party Quests",
        "description": "Guests complete mingling quests throughout the party and confirm each other on their phones.",
        "status": "gamma",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": True,
        "can_edit_content": True,
        "can_quick_start": True,
        "supports_ai_generation": True,
        "creation_modes": ["template", "ai", "manual", "quick_start"],
        "default_content_available": True,
        "embedded_authoring_supported": True,
        "requires_prepared_content_for_checkin": True,
        "policy_opt_in_capabilities": [
            "can_create_content",
            "can_edit_content",
            "supports_ai_generation",
            "embedded_authoring_supported",
            "requires_prepared_content_for_checkin",
        ],
        "checkin_friendly": True,
        "supports_late_join": True,
        "can_start_with_first_player": True,
        "default_for_checkin_supported": True,
        "auto_start_on_first_checkin_default": True,
        "checkin_join_policy": "resume_or_join",
        "content_schema": {
            "kind": "party_quests_setup_v1",
            "supported_media": [],
        },
        "result_summary_schema": "party_quests_result_v1",
        "config_schema": {
            "players": {"min": config.MIN_PARTY_QUESTS_PLAYERS, "recommended_min": 4, "max": config.MAX_PLAYERS_PER_ROOM},
            "duration_minutes": {"min": 10, "max": 240, "default": 90},
            "quests_per_player": {"min": 3, "max": 25, "default": 8},
            "confirmation_mode": {"default": "tap_confirm", "options": ["tap_confirm", "honor"]},
            "allow_late_join": {"default": True},
            "default_for_checkin": {"default": False},
            "auto_start_on_first_checkin": {"default": True},
            "checkin_join_policy": {"default": "resume_or_join", "options": ["resume_or_join", "host_started_only"]},
        },
    },
    {
        "id": "would_you_rather",
        "game_type": "would_you_rather",
        "runtime_type": "would_you_rather",
        "title": "Would You Rather",
        "description": "Pick between two funny options, then reveal where the room landed.",
        "status": "gamma",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "binary_choice_setup_v1",
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_WOULD_YOU_RATHER_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "rounds": {"min": 3, "max": 25, "default": 10},
            "scoring_modes": ["majority", "none"],
        },
    },
    {
        "id": "survey_says",
        "game_type": "survey_says",
        "runtime_type": "survey_says",
        "engine_family": "team_survey",
        "title": "Survey Says",
        "description": "Teams guess the top survey answers while the host reveals the board and tracks strikes.",
        "status": "gamma",
        "launchable": True,
        "host_app_supported": False,
        "supported_host_apps": [],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["quick_start", "settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "survey_says_setup_v1",
            "round_count": {"min": 1, "max": 20},
            "answers_per_round": {"min": 3, "max": 8},
            "supported_media": [],
        },
        "result_summary_schema": "survey_says_result_v1",
        "config_schema": {
            "players": {"min": config.MIN_SURVEY_SAYS_PLAYERS, "recommended_min": 6, "max": config.MAX_PLAYERS_PER_ROOM},
            "team_count": {"default": 2},
            "max_strikes": {"min": 1, "max": 5, "default": 3},
            "guess_time_seconds": {"min": 10, "max": 180, "default": 45},
        },
    },
    *generic_prompt_catalog_entries(config.MAX_PLAYERS_PER_ROOM),
    {
        "id": "never_have_i_ever",
        "game_type": "never_have_i_ever",
        "runtime_type": "never_have_i_ever",
        "title": "Never Have I Ever",
        "description": "Answer privately, then reveal the room split for each prompt.",
        "status": "gamma",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "confession_prompt_setup_v1",
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_NEVER_HAVE_I_EVER_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "rounds": {"min": 3, "max": 25, "default": 10},
            "safe_levels": ["family", "work", "party", "spicy"],
        },
    },
    {
        "id": "word_association",
        "game_type": "word_association",
        "runtime_type": "word_association",
        "title": "Word Association",
        "description": "Everyone submits the first word that comes to mind and matches score together.",
        "status": "gamma",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "word_seed_setup_v1",
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_WORD_ASSOCIATION_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "rounds": {"min": 3, "max": 25, "default": 10},
            "scoring_modes": ["majority", "none"],
        },
    },
    {
        "id": "acronym",
        "game_type": "acronym",
        "runtime_type": "acronym",
        "title": "Acronym Game",
        "description": "Expand random acronyms into silly phrases, then vote for the best one.",
        "status": "gamma",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "acronym_setup_v1",
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_ACRONYM_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "rounds": {"min": 3, "max": 20, "default": 8},
            "acronym_length": {"min": 2, "max": 8},
        },
    },
    {
        "id": "photo_clue",
        "game_type": "photo_clue",
        "runtime_type": "photo_clue",
        "engine_family": "image_games",
        "title": "Photo Clue",
        "description": "One player gets a secret phrase, submits a photo clue, and everyone guesses.",
        "status": "gamma",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": True,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "photo_clue_setup_v1",
            "supported_media": ["image"],
        },
        "config_schema": {
            "players": {"min": config.MIN_PHOTO_CLUE_PLAYERS, "recommended_min": 4, "max": config.MAX_PLAYERS_PER_ROOM},
            "rounds": {"min": 3, "max": 25, "default": 5},
            "photo_time_seconds": {"min": 30, "max": 300, "default": 90},
            "guess_time_seconds": {"min": 10, "max": 120, "default": 45},
        },
    },
    {
        "id": "poker",
        "game_type": "poker",
        "runtime_type": "poker",
        "engine_family": "cards",
        "title": "Party Poker",
        "description": "A no-money quick Hold'em tournament with play chips, folds, showdowns, and podium.",
        "status": "gamma",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": False,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "quick_holdem_setup_v1",
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_POKER_PLAYERS, "max": 10},
            "starting_stack": {"min": 200, "max": 10000, "default": 1000},
            "ante": {"min": 5, "max": 500, "default": 20},
            "decision_time_seconds": {"min": 10, "max": 90, "default": 25},
        },
    },
    {
        "id": "odd_question",
        "game_type": "odd_question",
        "runtime_type": "odd_question",
        "title": "Odd Question",
        "description": "Everyone answers the same question — except one player, who got a different one. Find them.",
        # Wired into the "simple social" family 2026-07-27 and verified over the wire, including
        # that a non-odd player never receives the minority prompt.
        "status": "gamma",
        "launchable": True,
        "host_app_supported": True,
        "supported_host_apps": ["revelry"],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "odd_question_pairs_v1",
            "supported_media": [],
        },
        "config_schema": {
            "players": {"min": config.MIN_ODD_QUESTION_PLAYERS, "max": config.MAX_PLAYERS_PER_ROOM},
            "rounds": {"min": 1, "max": 10, "default": 5},
        },
    },
    {
        "id": "impostor",
        "game_type": "impostor",
        "runtime_type": "impostor",
        "title": "Impostor",
        "description": "Everyone knows the secret word except one. Say a clue aloud, then vote on who's faking.",
        # The FIRST pass-and-play game (SPEC-PASS-AND-PLAY): one phone circulates instead of one
        # phone per player, so guests without a device can play. `interaction` is what the picker
        # badges and what code derives the pass-and-play family from — do NOT hand-list game ids.
        "interaction": "pass_and_play",
        "status": "gamma",
        "launchable": True,
        # Pass-and-play needs one physical device and a table. Embedding it in a host app that
        # assumes per-player phones would misrepresent how it's played, so keep it standalone
        # until the Revelry side understands the interaction model.
        "host_app_supported": False,
        "supported_host_apps": [],
        "supports_custom_content": True,
        "supports_images": False,
        "can_create_content": False,
        "can_edit_content": False,
        "can_quick_start": True,
        "supports_ai_generation": False,
        "creation_modes": ["settings"],
        "default_content_available": True,
        "embedded_authoring_supported": False,
        "content_schema": {
            "kind": "impostor_word_pairs_v1",
            "supported_media": [],
        },
        "config_schema": {
            # `players` here is SEATS the host types in, not connected devices.
            "players": {"min": config.MIN_IMPOSTOR_PLAYERS, "max": config.MAX_PASS_PLAY_SEATS},
            "rounds": {"min": 1, "max": 10, "default": 3},
            "clue_rounds": {"min": 1, "max": 4, "default": 2},
        },
    },
]

# Derived, never hand-listed. The occasion bingos shipped broken because three separate lists
# still said ['bingo','baby_bingo'] after new members were added; deriving from a property makes
# that class of drift impossible.
PASS_AND_PLAY_GAME_TYPES = frozenset(
    g["game_type"] for g in GAME_CATALOG if g.get("interaction") == "pass_and_play"
)

_MIN_PLAYERS_BY_RUNTIME = {
    "quiz": 1,
    "wmlt": config.MIN_WMLT_PLAYERS,
    "drawing": config.MIN_DRAWING_PLAYERS,
    "housie": config.MIN_HOUSIE_PLAYERS,
    "bingo": config.MIN_BINGO_PLAYERS,
    "musical_chairs": config.MIN_MUSICAL_CHAIRS_PLAYERS,
    "bluff": config.MIN_BLUFF_PLAYERS,
    "two_truths": config.MIN_TWO_TRUTHS_PLAYERS,
    "story_chain": config.MIN_STORY_CHAIN_PLAYERS,
    "common_ground": config.MIN_COMMON_GROUND_PLAYERS,
    "find_someone": config.MIN_FIND_SOMEONE_PLAYERS,
    "who_am_i": config.MIN_WHO_AM_I_PLAYERS,
    "chit_pull": config.MIN_CHIT_PULL_PLAYERS,
    "mafia": config.MIN_MAFIA_PLAYERS,
    "party_quests": config.MIN_PARTY_QUESTS_PLAYERS,
    "survey_says": config.MIN_SURVEY_SAYS_PLAYERS,
    "would_you_rather": config.MIN_WOULD_YOU_RATHER_PLAYERS,
    "never_have_i_ever": config.MIN_NEVER_HAVE_I_EVER_PLAYERS,
    "word_association": config.MIN_WORD_ASSOCIATION_PLAYERS,
    "acronym": config.MIN_ACRONYM_PLAYERS,
    "photo_clue": config.MIN_PHOTO_CLUE_PLAYERS,
    "poker": config.MIN_POKER_PLAYERS,
    "odd_question": config.MIN_ODD_QUESTION_PLAYERS,
    "impostor": config.MIN_IMPOSTOR_PLAYERS,
}


def _attach_player_minimums(catalog):
    for game in catalog:
        runtime_type = game.get("runtime_type") or game.get("game_type")
        min_players = _MIN_PLAYERS_BY_RUNTIME.get(runtime_type)
        if min_players is None:
            continue
        config_schema = game.setdefault("config_schema", {})
        players_schema = config_schema.setdefault("players", {})
        players_schema.setdefault("min", min_players)
        players_schema.setdefault("max", config.MAX_PLAYERS_PER_ROOM)
    return catalog


_attach_player_minimums(GAME_CATALOG)
attach_tv_capabilities(GAME_CATALOG)
attach_rules(GAME_CATALOG)
